config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  post 'sessions/create'
  get 'welcome/index'
  post 'users/create'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    resources :articles do
      resources :comments
    end
  end
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: {minimum: 5}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
  attr_accessor :remeber_token
  has_secure_password
  #用来加密remeber_token，然后保存到数据库中的remeber_digest中去
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  #生成随机的字符串
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  #每次登录成功或者注册后，都会调用remeber的方法，将remeber_token这个随机字符串加密后更新到数据库中的remeber_digest的值
  def remeber
    self.remeber_token = User.new_token
    self.update_attribute(:remeber_digest, User.digest(remeber_token))
  end
  #用来判断cookies[:remeber_token]中的值通过BCrypt加密后，是否与数据库中的一致
  def authenticated?(remeber_token)
    return false if remeber_digest.nil?
    BCrypt::Password.new(remeber_digest).is_password?(remeber_token)
  end
  #退出登录时调用，将数据库是的rember_digest值置为nil
  def forget
    self.update_attribute(:remember_digest, nil)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @user = User.find(params[:user_id])
    @article = @user.articles.new
  end

  def create
    @user = User.find(params[:user_id])
    @article = @user.articles.create(article_params)

    if @article.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def show
    @user = User.find(params[:user_id])
    @article = @user.articles.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @article = @user.articles.find(params[:id])
    @article.destroy
    redirect_to @user
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def new
  end

  def create
    name = params[:session][:name]
    password = params[:session][:password]
    #User.find_by_login(login)是新增加的一个类方法，用来实现name或者email的登录
    user = User.find_by_name(name)
    #authenticate是has_secure_password引入的一个方法，用来判断user的密码与页面中传过来的密码是否一致
    if user && user.authenticate(password)
      log_in(user) #SessionsHelper中的方法
      #判断是否要持续性的记住用户的登录状态
      params[:session][:remember_me] == "1" ? remember(user) : forget(user)
      redirect_to user_path(user)
    else
      flash.now[:danger] = "用户名或密码错误."
      render 'new'
    end
  end

  def destroy
    log_out if logged_in? #SessionsHelper中的方法
    redirect_to user_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
  def show
    @user = User.find(params[:id])
  end
  private
  def user_params
    params.require(:user).permit(:name, :password,:password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #一旦账号密码正确，则成功登录，同时在session中记录session[:user_id]
  def log_in(user)
    session[:user_id] = user.id
  end
  #如果用户允许在本地保存登录信息，则保存cookies
  def remember(user)
    #先把本次登录的remeber_token保存至数据库
    user.remeber
    #然后把remeber_token保存到cookies中，同时把user_id也保存在cookies中
    # cookies[:remeber_token] = { value: user.remeber_token, expires: 10.days.from_now.utc}
    # cookies.signed[:user_id] = { value: user.id, expires: 10.days.from_now.utc}
    cookies.permanent[:remeber_token] = user.remeber_token
    cookies.permanent.signed[:user_id] = user.id
  end
  #获取当前登录用户，如未登录，则为nil.@current_user这个实例变量是为了避免每次调用current_user方法都去查询一遍数据库的情况。
  def current_user
    #先判断session中是否为nil
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
      #再判断cookies中是否保存了登录信息
    else (user_id = cookies.signed[:user_id])
    user = User.find_by(id: user_id)
    #如果cookies中保存了，再用authenticated?这个方法判断cookies[:remeber_token]或者数据库中的remeber_digest是否一致。
    if user && user.authenticated?(cookies[:remember_token])
      log_in(user)
      @current_user = user
    end
    end
  end
  #用来判断用户是否登录的方法
  def logged_in?
    !current_user.nil?
  end
  #用来清空持久性登录信息
  def forget(user)
    user.forget #将user.remeber_digest重置为nil
    #删除cookies中的登录信息
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end
  #退出，同时删除session中的信息
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to '查看', user_article_path(article) %></td>
      <td><%= link_to '编辑', edit_user_article_path(article) %></td>
      <td><%= link_to '删除', [article.user, article],
                      method: :delete,
                      data: { confirm: '确定删除?' } %></td>
    </tr>

app/views/articles/_form.html.erb
<%= form_for([@user,@user.articles.build]) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> 禁止这篇文章被保存:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :标题 %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :内容 %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit :保存 %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>编辑文章</h1>

<%= render 'form' %>

<%= link_to '返回首页', articles_path %>

app/views/articles/index.html.erb
<h1>文章列表</h1>
<%= link_to '新建文章', new_article_path %>
<table>
  <tr>
    <th>标题</th>
    <th>内容</th>
    <th colspan="3"></th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to '查看', article_path(article) %></td>
      <td><%= link_to '编辑', edit_article_path(article) %></td>
      <td><%= link_to '删除', article_path(article),
                      method: :delete,
                      data: { confirm: '确定删除?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>新建文章</h1>
<%= render 'form' %>
<%= link_to '返回我的首页', user_path(@user) %>

app/views/articles/show.html.erb
<p>
  <strong>标题:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>内容:</strong>
  <%= @article.text %>
</p>
<h2>评论列表</h2>
<%= render @article.comments %>
<h2>添加评论:</h2>
<%= render 'comments/form'  %>
<%= link_to '编辑', edit_article_path(@article) %> |
<%= link_to '返回首页', articles_path %>|
<%= link_to '返回新建页', new_article_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>评论者:</strong>
  <%= comment.commenter %>
</p>

<p>
  <strong>评论:</strong>
  <%= comment.body %>
</p>
<p>
  <%= link_to '删除评论', [comment.article, comment],
              method: :delete,
              data: { confirm: '确认删除?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :评论者 %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :内容 %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        注册失败:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :名字 %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :密码 %><br>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :密码确认 %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit :保存 %>
  </p>
<% end %>

app/views/users/show.html.erb
<p>您好， <%= @user.name %></p>
<%= link_to '新建文章',new_user_article_path(@user) %>
<h1>我的文章列表</h1>
<table>
  <tr>
    <th>标题</th>
    <th>内容</th>
    <th colspan="3"></th>
  </tr>


<%= render @user.articles %>
</table>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to '登陆', controller: 'sessions',action: 'new' %>